{% set name = "sbpy" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6da03f502b971510275bc7306995e1142403ede5d3ec7b72d3bd6e21f807f424
  patches:
    - setup.cfg.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy >=1.13.0
    - astropy >=3.0
    - matplotlib-base
    - ads
    - synphot
    - astroquery >=0.4.1

test:
  imports:
    - sbpy
    - sbpy.units
    - sbpy.obsutil
    - sbpy.photometry

about:
  home: https://sbpy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: sbpy is a Python package for small-body planetary astronomy.
  description: |
    sbpy is a community effort to build a Python package for small-body
    planetary astronomy in the form of an Astropy affiliated package. The
    goal is to collect and implement well-tested and well-documented code
    for the scientific study of asteroids and comets, including (but not
    limited to) observation planning, photometric models, spectroscopic
    analysis, asteroid thermal models, lightcurve and shape tools, and
    access tools for relevant databases.
  doc_url: https://sbpy.readthedocs.io/
  dev_url: https://github.com/NASA-Planetary-Science/sbpy

extra:
  recipe-maintainers:
    - mwcraig
